server:
  port: 8080
  error:
    path: "/error"
    whitelabel:
      enabled: false  

spring:
  profiles:
    active:
      - prod
  servlet:
    multipart:
      max-file-size:
        128MB
      max-request-size:
        128MB

  mail:
    host: ${mailHost}
    port: 587
    username: ${mailUsername}
    password: ${mailPassword}
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true