server:
  port: 8080
  error:
    path: "/error"
    whitelabel:
      enabled: false  

spring:
  # profiles:
  #   active:
  #     - test
  datasource:
    url: "jdbc:mysql://localhost:3306/portfolioDatabase"
    username: root
    password: class Kushal{PASS}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size:
        128MB
      max-request-size:
        128MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: kushalshah821@gmail.com
    password: wfjsvggpbijxfhap
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true