spring:
  config:
    activate:
      on-profile:
        - local
  datasource:
    url: "jdbc:mysql://localhost:3306/${localDBName}"
    username: ${localDBUserName}
    password: ${localDBPassword}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update